### ISSUE TITLE
Matrix request: miniature taxa

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-data#14]
miniature-matrix.xml for the taxa listed below. Please send two versions - with and without supporting states, and please include both variable and invariant characters:

Taxa (mini and non-mini) (Note: not all taxa currently in VTO)
Neostethus geminus
Neostethus borneensis
Phenacostethus posthon
Phenacostethus smithi
Phenacostethus trewavasae
Oryzias mekongensis
Oryzias minutillus
Axelrodia lindeae
Axelrodia riesei
Axelrodia stigmatias
Microschemobrycon elongatus
Microschemobrycon meyburgi
Oxybrycon parvulus
Tyttobrycon dorsimaculatus
Tyttobrycon hamatus
Tyttobrycon marajoara
Tyttobrycon spinosus
Tyttobrycon xeruini
Amazonspinther dalmata
Cheirodon luelingi
Nanocheirodon insignis
Odontostilbe gracilis
Odontostilbe littoris
Serrapinnus kriegi
Spintherobolus broccae
Priocharax ariel
Priocharax nanus
Priocharax pygmaeus
Bryconella pallidifrons
Erythrocharax altipinnis
Tucanoichthys tucano
Creagrutus maracaiboensis
Creagrutus nigrostigmatus
Cyanogaster noctivaga
Iotabrycon praecox
Pterobrycon landoni
Scopaeocharax atopodus
Scopaeocharax rhinodus
Trochilocharax ornatus
Tyttocharax cochui
Tyttocharax madeirae
Tyttocharax metae
Tyttocharax tambopatensis
Xenurobrycon coracoralinae
Xenurobrycon heterodon
Xenurobrycon macropus
Xenurobrycon polyancistrus
Xenurobrycon pteropus
Hemigrammus aereus
Hemigrammus iota
Hemigrammus luelingi
Hemigrammus tridens
Hyphessobrycon albolineatus
Hyphessobrycon amandae
Hyphessobrycon arianae
Hyphessobrycon axelrodi
Hyphessobrycon catableptus
Hyphessobrycon ecuadorensis
Hyphessobrycon elachys
Hyphessobrycon gracilior
Hyphessobrycon griemi
Hyphessobrycon haraldschultzi
Hyphessobrycon heteresthes
Hyphessobrycon hildae
Hyphessobrycon loretoensis
Hyphessobrycon minimus
Hyphessobrycon parvellus
Hyphessobrycon roseus
Hyphessobrycon saizi
Hyphessobrycon tenuis
Hyphessobrycon tropis
Hyphessobrycon tukunai
Paracheirodon innesi
Paracheirodon simulans
Ammocryptocharax minutus
Characidium bahiense
Characidium heinianum
Characidium mirim
Characidium pteroides
Elachocharax geryi
Elachocharax junki
Elachocharax mitopterus
Elachocharax pulcher
Klausewitzia ritae
Microcharacidium eleotrioides
Microcharacidium geryi
Microcharacidium gnomus
Microcharacidium weitzmani
Odontocharacidium aphanes
Carnegiella myersi
Carnegiella schereri
Nannostomus anduzei
Nannostomus britskii
Nannostomus minimus
Amazonsprattus scintilla
Anchoviella manamensis
Sundasalanx microps
Sundasalanx precox
Barbucca diabolica
Homaloptera tweediei
Neohomaloptera johorensis
Tuberoschistura cambodgiensis
Boraras brigittae
Boraras maculatus
Boraras merah
Boraras micros
Boraras naevus
Boraras urophthalmoides
Danio erythromicron
Danio margaritatus
Danionella dracula
Danionella mirifica
Danionella priapus
Danionella translucida
Horadandia atukorali
Microrasbora kubotai
Microrasbora nana
Microrasbora rubescens
Paedocypris carbunculus
Paedocypris micromegethes
Paedocypris progenetica
Rasbora kalbarensis
Rasbora spilocerca
Sawbwa resplendens
Sundadanio axelrodi
Tanichthys micagemmae
Cnesterodon raddai
Gambusia dominicensis
Gambusia marshi
Gambusia sexradiata
Girardinus cubensis
Limia dominicensis
Limia garnieri
Limia heterandria
Limia immaculata
Micropoecilia minima
Neoheterandria cana
Neoheterandria elegans
Neoheterandria tridentiger
Pamphorichthys araguaiensis
Pamphorichthys hasemani
Pamphorichthys hollandi
Pamphorichthys minor
Pamphorichthys pertapeh
Pamphorichthys scalpridens
Phallichthys quadripunctatus
Phallichthys tico
Phalloptychus eigenmanni
Phallotorynus dispilos
Phallotorynus psittakos
Phallotorynus victoriae
Poecilia hasemani
Poecilia parae
Poeciliopsis baenschi
Priapichthys panamensis
Pseudopoecilia austrocolumbiana
Quintana atrizona
Scolichthys iota
Xiphophorus continens
Fluviphylax obscurus
Fluviphylax palikur
Fluviphylax pygmaeus
Fluviphylax simplex
Fluviphylax zonatus
Laimosemion jauaperi
Laimosemion kirovskyi
Laimosemion romeri
Laimosemion uatuman
Laimosemion ubim
Leptolebias itanhaensis
Leptolebias marmoratus
Melanorivulus egens
Melanorivulus paracatuensis
Melanorivulus rossoi
Melanorivulus rutilicaudus
Notholebias cruzi
Notholebias vermiculatus
Plesiolebias aruana
Plesiolebias glaucopterus
Plesiolebias lacerdai
Simpsonichthys cholopteryx
Simpsonichthys nigromaculatus
Simpsonichthys parallelus
Spectrolebias costai
Spectrolebias reticulatus
Spectrolebias semiocellatus
Stenolebias bellus
Stenolebias damascenoi
Aplocheilus parvus
Leptophilypnion fittkaui
Leptophilypnion pusillus
Microphilypnus acangaquara
Microphilypnus macrostoma
Microphilypnus tapajosensis
Microphilypnus ternetzi
Gobiosoma yucatanum
Trimmatom nanus
Trimmatom offucius
Schindleria brevipinguis
Schindleria pietschmanni
Schindleria praematura
Brachygobius aggregatus
Brachygobius kabiliensis
Gobiopterus brachypterus
Gobiopterus chuno
Pseudogobius oratai
Cromeria nilotica
Cromeria occidentalis
Grasseichthys gabonensis
Apistogramma juruensis
Apistogramma piauiensis
Apistogramma staecki
Elassoma alabamae
Betta rutilans
Parosphromenus anjunganesis
Parosphromenus filamentosus
Parosphromenus ornaticauda
Parosphromenus parvulus
Acanthobunocephalus nicoi
Dupouyichthys sapito
Hoplomyzon papillatus
Micromyzon akamai
Astroblepus chimborazoi
Gelanoglanis nanonocticolus
Tatia marthae
Aspidoras brunneus
Aspidoras carvalhoi
Aspidoras pauciradiatus
Corydoras boehlkei
Corydoras cochui
Corydoras gracilis
Corydoras habrosus
Corydoras hastatus
Corydoras pygmaeus
Denticetopsis royeroi
Denticetopsis sauli
Physopyxis ananas
Physopyxis cristata
Erethistes maesotensis
Horiomyzon retropinnatus
Nannoplecostomus eleonorae
Otocinclus tapirape
Parotocinclus amazonensis
Parotocinclus collinsae
Parotocinclus halbothi
Microglanis zonatus
Scoloplax baileyi
Scoloplax baskini
Scoloplax dicra
Scoloplax distolothrix
Scoloplax dolicholophia
Scoloplax empousa
Pygidianops amphioxus
Ammoglanis amapaensis
Ammoglanis diaphanus
Ammoglanis pulex
Malacoglanis gelatinosus
Microcambeva draco
Pygidianops cuao
Pygidianops eigenmanni
Pygidianops magoi
Sarcoglanis simplex
Typhlobelus guacamaya
Typhlobelus macromycterus
Schultzichthys gracilis
Trichomycterus anhanga
Trichomycterus hasemani
Trichomycterus johnsoni
Trichomycterus santaeritae
Miuroglanis platycephalus
Tridensimilis venezuelae
Tridentopsis cahuali
Tridentopsis pearsoni
Tridentopsis tocantinsi
Danio rerio
Creagrutus ouranonastes
Creagrutus peruanus
Creagrutus muelleri
Parakneria spekii
Parakneria ladigesi
Parakneria vilhenae
Ammocryptocharax elegans
Characidium interruptum
Characidium lanei
Spintherobolus leptoura
Pseudocheirodon terrabae
Pseudocheirodon arnoldi

**Comment by balhoff** [comment]
From @wdahdul

**Comment by balhoff** [comment]
@wdahdul can you remind me what the anatomy query for this should be?

**Comment by wdahdul** [comment]
part of skeletal system

**Comment by balhoff** [comment]
Done.
