### ISSUE TITLE
Merge additional matrix data into existing nexml file (Mattox et al 2016)

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-data#23]
Merge the following matrix (147 characters for 2 taxa):
https://docs.google.com/spreadsheets/d/1T0BtOog6zxFwHTjCtCxNTwbo1yCcYH_dcF1P94Hbros/edit?usp=sharing

... into the nexml file for Mattox_etal_2016_Priocharax.xml (see miniature monographs folder).

Please move this ticket if there's a more appropriate tracker for it. Thanks!

**Comment by wdahdul** [comment]
Pertains to https://github.com/phenoscape/phenoscape-kb-web-ui/issues/45

**Comment by balhoff** [comment]
The data have been merged in and synced in Dropbox. Next step is to do EQ annotation on the new characters and then it should be good to go.

**Comment by wdahdul** [comment]
Tova finished EQ annotation on this file last week.
